### ISSUE TITLE
Enable Used Item Counter - help text is too big and is not showing completely

### ISSUE THREAD

**Issue by brunoramoslu** [raduprv/Eternal-Lands#115]
![image](https://user-images.githubusercontent.com/3391955/104456559-24ca3e00-55a9-11eb-80c6-99aac0ed2abe.png)

**Comment by brunoramoslu** [comment]
I'm unsure on how to fix this, so won't try a fix at least not right away.

If I start working on this I'll update the issue first.

**Comment by pjbroad** [comment]
I was wondering about this too.  I see we have several options:
- Reduce the description text length for options that are too long.
- Add another line to the window, making more room.
- Make the font smaller for the text until all options fit.
A more radical option:
- Change the description text to be like help text (or the achievements description) and remove the unused section from the window gaining a smaller window.
I'm sure there are more.....

**Comment by gvissers** [comment]
5. Use a different font: 
![long-help-text](https://user-images.githubusercontent.com/1096355/105605855-ae8ebe00-5d96-11eb-9d4f-a2aa9d83e71a.png)

I don't like option 4 ( the help text) too much, if at all possible I would try option 1. I also think the help text in this case could be improved. What previous versions will crash when we save item counters? BTW: do they crash at at all (is this related to the JSON changes? because in that case I would expect older clients to simply not load the new file at all).

We could try option 3 (up to a point) if we really need to fit things in. I'll have a look to see if I can figure out how to best do that.

**Comment by pjbroad** [comment]
Before the font changes, when adding new descriptions I've made sure the text fitted.  I've also fixed the text where I've spotted it too was long.  After the font changes, I've not gone back to check all the descriptions, plus the user has more control over the font which can make some descriptions which previously fit, or fix for some people, not fit for them.  I'm not sure how a different font would work as the user has the choice of font.

As for this particular options and the counters crashing.  When I added the "Use" counter, it increased the number of counter records and I realised that the counter load code did not take account of the number of counters.  So if you used the new client creating an new counters file, the switched back to the old client, the load counters function would read an addition record with an out of bounds error.   I fixed that for the updated version of the code but the "current" client that is on the EL downloads page does not cope; hence the warning.  This sort of madness was one motivation for the JSON file changes.

**Comment by gvissers** [comment]
> I'm not sure how a different font would work as the user has the choice of font.

Nah, that was more tongue in cheek. Should've added s smiley.

> plus the user has more control over the font which can make some descriptions which previously fit, or fix for some people, not fit for them

Good point. 

> As for this particular options and the counters crashing. When I added the "Use" counter, it increased the number of counter records and I realised that the counter load code did not take account of the number of counters. So if you used the new client creating an new counters file, the switched back to the old client, the load counters function would read an addition record with an out of bounds error. I fixed that for the updated version of the code but the "current" client that is on the EL downloads page does not cope; hence the warning. This sort of madness was one motivation for the JSON file changes.

Right, so this warning is from before the JSON changes. Is it still current?

Anyway, I have pushed a fix that will adjust the scale when the text becomes too large.

**Comment by pjbroad** [comment]
> Right, so this warning is from before the JSON changes. Is it still current?
Its still current as the version that may crash is still out in the wild and the one that is available from the downloads page.  We can remove it warning after the next release....  Also, I'd like to make the JSON files the only option, so remove the choice before the next update, then remove the old code after that.

**Comment by pjbroad** [comment]
I'm assuming this is OK to close as now fixed.
